# Generated by Django 5.1 on 2024-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
